import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Create categories
  const thailandCategory = await prisma.category.upsert({
    where: { id: "category_thailand" },
    update: {},
    create: {
      id: "category_thailand",
      billboard: "Thailand",
      billboardId: "thailand",
      category: "Thailand",
    },
  });

  const singaporeCategory = await prisma.category.upsert({
    where: { id: "category_singapore" },
    update: {},
    create: {
      id: "category_singapore",
      billboard: "Singapore",
      billboardId: "singapore",
      category: "Singapore",
    },
  });

  const usaCategory = await prisma.category.upsert({
    where: { id: "category_usa" },
    update: {},
    create: {
      id: "category_usa",
      billboard: "USA",
      billboardId: "usa",
      category: "USA",
    },
  });

  const japanCategory = await prisma.category.upsert({
    where: { id: "category_japan" },
    update: {},
    create: {
      id: "category_japan",
      billboard: "Japan",
      billboardId: "japan",
      category: "Japan",
    },
  });

  const europeCategory = await prisma.category.upsert({
    where: { id: "category_europe" },
    update: {},
    create: {
      id: "category_europe",
      billboard: "Europe",
      billboardId: "europe",
      category: "Europe",
    },
  });

  const asiaCategory = await prisma.category.upsert({
    where: { id: "category_asia" },
    update: {},
    create: {
      id: "category_asia",
      billboard: "Asia",
      billboardId: "asia",
      category: "Asia",
    },
  });

  const koreaCategory = await prisma.category.upsert({
    where: { id: "category_korea" },
    update: {},
    create: {
      id: "category_korea",
      billboard: "Korea",
      billboardId: "korea",
      category: "Korea",
    },
  });

  const australiaCategory = await prisma.category.upsert({
    where: { id: "category_australia" },
    update: {},
    create: {
      id: "category_australia",
      billboard: "Australia",
      billboardId: "australia",
      category: "Australia",
    },
  });

  // Create products - eSIM/SIM Thailand (6 products)
  const thaiProducts = [
    {
      title: "eSIM Thái Lan - 3GB/7 ngày",
      description: "Gói eSIM Thái Lan 3GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/thailand.png"]),
      category: "Thailand",
      categoryId: thailandCategory.id,
      price: 85000,
      finalPrice: 75000,
      discount: 12,
      featured: true,
      country: "Thái Lan",
      region: "Đông Nam Á",
      dataPlan: "3GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Thái Lan - 8GB/15 ngày",
      description: "Gói eSIM Thái Lan 8GB data, hiệu lực 15 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/thailand.png"]),
      category: "Thailand",
      categoryId: thailandCategory.id,
      price: 120000,
      featured: true,
      country: "Thái Lan",
      region: "Đông Nam Á",
      dataPlan: "8GB",
      validityDays: 15,
      simType: "eSIM",
    },
    {
      title: "eSIM Thái Lan - 15GB/30 ngày",
      description: "Gói eSIM Thái Lan 15GB data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/thailand.png"]),
      category: "Thailand",
      categoryId: thailandCategory.id,
      price: 180000,
      finalPrice: 160000,
      discount: 11,
      featured: true,
      country: "Thái Lan",
      region: "Đông Nam Á",
      dataPlan: "15GB",
      validityDays: 30,
      simType: "eSIM",
    },
    {
      title: "SIM Thái Lan - 5GB/7 ngày",
      description: "Gói SIM Thái Lan 5GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/thailand.png"]),
      category: "Thailand",
      categoryId: thailandCategory.id,
      price: 95000,
      featured: false,
      country: "Thái Lan",
      region: "Đông Nam Á",
      dataPlan: "5GB",
      validityDays: 7,
      simType: "SIM",
    },
    {
      title: "SIM Thái Lan - 20GB/30 ngày",
      description: "Gói SIM Thái Lan 20GB data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/thailand.png"]),
      category: "Thailand",
      categoryId: thailandCategory.id,
      price: 220000,
      featured: false,
      country: "Thái Lan",
      region: "Đông Nam Á",
      dataPlan: "20GB",
      validityDays: 30,
      simType: "SIM",
    },
    {
      title: "eSIM Thái Lan - Unlimited/7 ngày",
      description: "Gói eSIM Thái Lan Unlimited data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/thailand.png"]),
      category: "Thailand",
      categoryId: thailandCategory.id,
      price: 150000,
      featured: true,
      country: "Thái Lan",
      region: "Đông Nam Á",
      dataPlan: "Unlimited",
      validityDays: 7,
      simType: "eSIM",
    },
  ];

  // Create products - eSIM Singapore (5 products)
  const sgProducts = [
    {
      title: "eSIM Singapore - 5GB/7 ngày",
      description: "Gói eSIM Singapore 5GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/singapore.png"]),
      category: "Singapore",
      categoryId: singaporeCategory.id,
      price: 120000,
      featured: true,
      country: "Singapore",
      region: "Đông Nam Á",
      dataPlan: "5GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Singapore - 10GB/14 ngày",
      description: "Gói eSIM Singapore 10GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/singapore.png"]),
      category: "Singapore",
      categoryId: singaporeCategory.id,
      price: 180000,
      featured: true,
      country: "Singapore",
      region: "Đông Nam Á",
      dataPlan: "10GB",
      validityDays: 14,
      simType: "eSIM",
    },
    {
      title: "eSIM Singapore & Malaysia - 12GB/14 ngày",
      description: "Gói eSIM Singapore & Malaysia 12GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/sing-malay.png"]),
      category: "Singapore",
      categoryId: singaporeCategory.id,
      price: 220000,
      finalPrice: 200000,
      discount: 9,
      featured: true,
      country: "Singapore & Malaysia",
      region: "Đông Nam Á",
      dataPlan: "12GB",
      validityDays: 14,
      simType: "eSIM",
    },
    {
      title: "SIM Singapore - 8GB/14 ngày",
      description: "Gói SIM Singapore 8GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/singapore.png"]),
      category: "Singapore",
      categoryId: singaporeCategory.id,
      price: 160000,
      featured: false,
      country: "Singapore",
      region: "Đông Nam Á",
      dataPlan: "8GB",
      validityDays: 14,
      simType: "SIM",
    },
    {
      title: "eSIM Singapore - Unlimited/30 ngày",
      description: "Gói eSIM Singapore Unlimited data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/singapore.png"]),
      category: "Singapore",
      categoryId: singaporeCategory.id,
      price: 350000,
      featured: true,
      country: "Singapore",
      region: "Đông Nam Á",
      dataPlan: "Unlimited",
      validityDays: 30,
      simType: "eSIM",
    },
  ];

  // Create products - eSIM USA (6 products)
  const usaProducts = [
    {
      title: "eSIM Mỹ - 5GB/7 ngày",
      description: "Gói eSIM Mỹ 5GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/usa.png"]),
      category: "USA",
      categoryId: usaCategory.id,
      price: 180000,
      featured: true,
      country: "Mỹ",
      region: "Châu Mỹ",
      dataPlan: "5GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Mỹ - 15GB/15 ngày",
      description: "Gói eSIM Mỹ 15GB data, hiệu lực 15 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/usa.png"]),
      category: "USA",
      categoryId: usaCategory.id,
      price: 280000,
      featured: true,
      country: "Mỹ",
      region: "Châu Mỹ",
      dataPlan: "15GB",
      validityDays: 15,
      simType: "eSIM",
    },
    {
      title: "eSIM Mỹ - 20GB/30 ngày",
      description: "Gói eSIM Mỹ 20GB data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/usa.png"]),
      category: "USA",
      categoryId: usaCategory.id,
      price: 450000,
      finalPrice: 400000,
      discount: 11,
      featured: true,
      country: "Mỹ",
      region: "Châu Mỹ",
      dataPlan: "20GB",
      validityDays: 30,
      simType: "eSIM",
    },
    {
      title: "eSIM Mỹ & Canada - Unlimited/30 ngày",
      description: "Gói eSIM Mỹ & Canada Unlimited data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/usa-canada.png"]),
      category: "USA",
      categoryId: usaCategory.id,
      price: 650000,
      featured: true,
      country: "Mỹ & Canada",
      region: "Châu Mỹ",
      dataPlan: "Unlimited",
      validityDays: 30,
      simType: "eSIM",
    },
    {
      title: "SIM Mỹ - 10GB/15 ngày",
      description: "Gói SIM Mỹ 10GB data, hiệu lực 15 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/usa.png"]),
      category: "USA",
      categoryId: usaCategory.id,
      price: 250000,
      featured: false,
      country: "Mỹ",
      region: "Châu Mỹ",
      dataPlan: "10GB",
      validityDays: 15,
      simType: "SIM",
    },
    {
      title: "eSIM Mỹ - 50GB/30 ngày",
      description: "Gói eSIM Mỹ 50GB data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/usa.png"]),
      category: "USA",
      categoryId: usaCategory.id,
      price: 550000,
      featured: true,
      country: "Mỹ",
      region: "Châu Mỹ",
      dataPlan: "50GB",
      validityDays: 30,
      simType: "eSIM",
    },
  ];

  // Create products - eSIM Japan (5 products)
  const japanProducts = [
    {
      title: "eSIM Nhật Bản - 3GB/7 ngày",
      description: "Gói eSIM Nhật Bản 3GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/japan.png"]),
      category: "Japan",
      categoryId: japanCategory.id,
      price: 150000,
      featured: true,
      country: "Nhật Bản",
      region: "Châu Á",
      dataPlan: "3GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Nhật Bản - 5GB/7 ngày",
      description: "Gói eSIM Nhật Bản 5GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/japan.png"]),
      category: "Japan",
      categoryId: japanCategory.id,
      price: 280000,
      featured: true,
      country: "Nhật Bản",
      region: "Châu Á",
      dataPlan: "5GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Nhật Bản - 10GB/14 ngày",
      description: "Gói eSIM Nhật Bản 10GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/japan.png"]),
      category: "Japan",
      categoryId: japanCategory.id,
      price: 420000,
      featured: true,
      country: "Nhật Bản",
      region: "Châu Á",
      dataPlan: "10GB",
      validityDays: 14,
      simType: "eSIM",
    },
    {
      title: "eSIM Nhật & Hàn - 15GB/14 ngày",
      description: "Gói eSIM Nhật & Hàn 15GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/japan-korea.png"]),
      category: "Japan",
      categoryId: japanCategory.id,
      price: 550000,
      finalPrice: 500000,
      discount: 9,
      featured: true,
      country: "Nhật & Hàn",
      region: "Châu Á",
      dataPlan: "15GB",
      validityDays: 14,
      simType: "eSIM",
    },
    {
      title: "SIM Nhật Bản - 8GB/14 ngày",
      description: "Gói SIM Nhật Bản 8GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/japan.png"]),
      category: "Japan",
      categoryId: japanCategory.id,
      price: 380000,
      featured: false,
      country: "Nhật Bản",
      region: "Châu Á",
      dataPlan: "8GB",
      validityDays: 14,
      simType: "SIM",
    },
  ];

  // Create products - eSIM Europe (5 products)
  const europeProducts = [
    {
      title: "eSIM Châu Âu - 5GB/7 ngày",
      description: "Gói eSIM Châu Âu 5GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/europe.png"]),
      category: "Europe",
      categoryId: europeCategory.id,
      price: 200000,
      featured: true,
      country: "Châu Âu",
      region: "Châu Âu",
      dataPlan: "5GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Châu Âu - 15GB/15 ngày",
      description: "Gói eSIM Châu Âu 15GB data, hiệu lực 15 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/europe.png"]),
      category: "Europe",
      categoryId: europeCategory.id,
      price: 350000,
      featured: true,
      country: "Châu Âu",
      region: "Châu Âu",
      dataPlan: "15GB",
      validityDays: 15,
      simType: "eSIM",
    },
    {
      title: "eSIM Châu Âu - 30GB/30 ngày",
      description: "Gói eSIM Châu Âu 30GB data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/europe.png"]),
      category: "Europe",
      categoryId: europeCategory.id,
      price: 550000,
      finalPrice: 500000,
      discount: 9,
      featured: true,
      country: "Châu Âu",
      region: "Châu Âu",
      dataPlan: "30GB",
      validityDays: 30,
      simType: "eSIM",
    },
    {
      title: "eSIM Anh & Pháp - 20GB/14 ngày",
      description: "Gói eSIM Anh & Pháp 20GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/europe.png"]),
      category: "Europe",
      categoryId: europeCategory.id,
      price: 450000,
      featured: true,
      country: "Anh & Pháp",
      region: "Châu Âu",
      dataPlan: "20GB",
      validityDays: 14,
      simType: "eSIM",
    },
    {
      title: "SIM Châu Âu - 10GB/15 ngày",
      description: "Gói SIM Châu Âu 10GB data, hiệu lực 15 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/europe.png"]),
      category: "Europe",
      categoryId: europeCategory.id,
      price: 300000,
      featured: false,
      country: "Châu Âu",
      region: "Châu Âu",
      dataPlan: "10GB",
      validityDays: 15,
      simType: "SIM",
    },
  ];

  // Create products - eSIM Korea (4 products)
  const koreaProducts = [
    {
      title: "eSIM Hàn Quốc - 5GB/7 ngày",
      description: "Gói eSIM Hàn Quốc 5GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/korea.png"]),
      category: "Korea",
      categoryId: koreaCategory.id,
      price: 180000,
      featured: true,
      country: "Hàn Quốc",
      region: "Châu Á",
      dataPlan: "5GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Hàn Quốc - 10GB/14 ngày",
      description: "Gói eSIM Hàn Quốc 10GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/korea.png"]),
      category: "Korea",
      categoryId: koreaCategory.id,
      price: 320000,
      featured: true,
      country: "Hàn Quốc",
      region: "Châu Á",
      dataPlan: "10GB",
      validityDays: 14,
      simType: "eSIM",
    },
    {
      title: "eSIM Hàn Quốc - 20GB/30 ngày",
      description: "Gói eSIM Hàn Quốc 20GB data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/korea.png"]),
      category: "Korea",
      categoryId: koreaCategory.id,
      price: 480000,
      finalPrice: 430000,
      discount: 10,
      featured: true,
      country: "Hàn Quốc",
      region: "Châu Á",
      dataPlan: "20GB",
      validityDays: 30,
      simType: "eSIM",
    },
    {
      title: "SIM Hàn Quốc - 8GB/14 ngày",
      description: "Gói SIM Hàn Quốc 8GB data, hiệu lực 14 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/korea.png"]),
      category: "Korea",
      categoryId: koreaCategory.id,
      price: 280000,
      featured: false,
      country: "Hàn Quốc",
      region: "Châu Á",
      dataPlan: "8GB",
      validityDays: 14,
      simType: "SIM",
    },
  ];

  // Create products - eSIM Australia (4 products)
  const australiaProducts = [
    {
      title: "eSIM Úc - 5GB/7 ngày",
      description: "Gói eSIM Úc 5GB data, hiệu lực 7 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/australia.png"]),
      category: "Australia",
      categoryId: australiaCategory.id,
      price: 220000,
      featured: true,
      country: "Úc",
      region: "Châu Đại Dương",
      dataPlan: "5GB",
      validityDays: 7,
      simType: "eSIM",
    },
    {
      title: "eSIM Úc - 15GB/15 ngày",
      description: "Gói eSIM Úc 15GB data, hiệu lực 15 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/australia.png"]),
      category: "Australia",
      categoryId: australiaCategory.id,
      price: 380000,
      featured: true,
      country: "Úc",
      region: "Châu Đại Dương",
      dataPlan: "15GB",
      validityDays: 15,
      simType: "eSIM",
    },
    {
      title: "eSIM Úc - 25GB/30 ngày",
      description: "Gói eSIM Úc 25GB data, hiệu lực 30 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/australia.png"]),
      category: "Australia",
      categoryId: australiaCategory.id,
      price: 520000,
      finalPrice: 470000,
      discount: 10,
      featured: true,
      country: "Úc",
      region: "Châu Đại Dương",
      dataPlan: "25GB",
      validityDays: 30,
      simType: "eSIM",
    },
    {
      title: "SIM Úc - 10GB/15 ngày",
      description: "Gói SIM Úc 10GB data, hiệu lực 15 ngày, hỗ trợ 4G/5G",
      imageURLs: JSON.stringify(["https://kemal-web-storage.s3.eu-north-1.amazonaws.com/australia.png"]),
      category: "Australia",
      categoryId: australiaCategory.id,
      price: 320000,
      featured: false,
      country: "Úc",
      region: "Châu Đại Dương",
      dataPlan: "10GB",
      validityDays: 15,
      simType: "SIM",
    },
  ];

  // Insert all products
  const allProducts = [
    ...thaiProducts,
    ...sgProducts,
    ...usaProducts,
    ...japanProducts,
    ...europeProducts,
    ...koreaProducts,
    ...australiaProducts,
  ];

  for (let i = 0; i < allProducts.length; i++) {
    const product = allProducts[i];
    // Create simple ID without special characters
    const simpleId = `product_${i + 1}`;
    
    await prisma.product.upsert({
      where: { id: simpleId },
      update: {},
      create: {
        id: simpleId,
        ...product,
      },
    });
  }

  console.log("✅ Database seeded successfully!");
  console.log(`   Created ${allProducts.length} products`);
  console.log(`   Created 8 categories`);
  console.log(`   Countries: Thailand, Singapore, USA, Japan, Europe, Korea, Australia`);
  console.log(`   Product types: eSIM and SIM cards`);
  console.log(`   Data plans: 3GB to Unlimited`);
  console.log(`   Validity: 7 to 30 days`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });